#NAME: Erica Xie
#EMAIL: ericaxie@ucla.edu
#ID: 404720875

default: dist

clean:
	rm -f lab4a-404920875.tar.gz

dist:
	tar czf lab4a-404920875.tar.gz build_run.png connected.png copy.png git.png my_beaglebone.jpg Makefile README
