#NAME: Erica Xie, Michelle Lam
#EMAIL: ericaxie@ucla.edu, laammichelle@gmail.com
#ID: 404920875, 404926523

default:
	python link.py

clean:
	rm -f lab3b-404926523.tar.gz lab3b

dist:
	tar czf lab3b-404926523.tar.gz Makefile README lab3b.py link.py
