#!/bin/bash

rm lab2_add.csv
touch lab2_add.csv

declare -a THREADS
declare -a ITER
declare -a ITER2 

THREADS=(1, 2, 4, 8, 12)
ITER=(10, 20, 40, 80, 100, 1000, 10000, 100000)
ITER2=(100, 1000, 10000, 100000)

for i in ${THREADS[@]}  
do
    for j in ${ITER[@]}
    do
	./lab2_add --iterations=$j --threads=$i --yield >> lab2_add.csv
    done
    for j in ${ITER2[@]}
    do
	./lab2_add --iterations=$j --threads=$i >> lab2_add.csv
    done
    ./lab2_add --iterations=10000 --threads=$i --yield --sync=m >> lab2_add.csv
    ./lab2_add --iterations=1000 --threads=$i --yield --sync=s >> lab2_add.csv
    ./lab2_add --iterations=1000 --threads=$i --yield --sync=c >> lab2_add.csv
    ./lab2_add --iterations=10000 --threads=$i --sync=m >> lab2_add.csv
    ./lab2_add --iterations=10000 --threads=$i --sync=s >> lab2_add.csv
    ./lab2_add --iterations=10000 --threads=$i --sync=c >> lab2_add.csv
done
